### ISSUE TITLE
how can I pass parameters to the child process

### ISSUE THREAD

**Issue by BrannonKing** [jasonrohrer/wallClockProfiler#2]
I want to be able to send parameters to my process that I am profiling. I tried passing them like this "program -param1 -param2". I also tried passing them individually on the command line (aka, without the quotes). This sent the profiler into an infinite loop.

**Comment by jasonrohrer** [comment]
Fixed in  5f1ed5ce10a25afc54d26d1cfbe3e615cd2544d9

You can now include arguments in quotes with your program name:

./wallClockProfiler 20 "program param1 param2"
