### ISSUE TITLE
primary thread alone is insufficient

### ISSUE THREAD

**Issue by BrannonKing** [jasonrohrer/wallClockProfiler#3]
The tool needs to grab the stack frames for all threads, not just the default thread. Perhaps this link helps: https://stackoverflow.com/questions/18391808/how-to-get-the-backtrace-for-all-the-threads-in-gdb.

**Comment by jasonrohrer** [comment]
I generally avoid threads myself, so I guess this is outside of the scope of the program that I wanted to build here....

But you're right---this would be totally useless on a multi-threaded program.
