### ISSUE TITLE
flame graph support

### ISSUE THREAD

**Issue by stefantalpalaru** [jasonrohrer/wallClockProfiler#5]
Turns out that the full GDB stack traces are enough to make flame graphs: https://github.com/brendangregg/FlameGraph/pull/239

Example output (no JS allowed in here):
![img](https://gist.githubusercontent.com/stefantalpalaru/f2eb4412ea56149967f0339ddc984ab6/raw/e70cc6a0f0a239cb2c43210c9139265674c90901/profile_19_300.svg?sanitize=1)

**Comment by jasonrohrer** [comment]
Cool!  I'm not really sure how to read this.

The supported KCacheGrind viewer has something similar, but it's more like a box area subdivided based on fraction of time spent.
